config/routes.rb
Rails.application.routes.draw do


  get 'iscsi/index'

  get 'nfs/index'

  get 'fstab/index'
  get 'fstab/remove'
  
  get 'samba/index'
  get 'samba/install'
  get 'samba/delete'
  
  post 'samba/createshare' => "samba#createshare", :via => :post, :as => :samba_createshare

  get 'firewall/index'
  get 'firewall/removeservice', :via => :get, :as => :firewall_removeservice
  get 'firewall/removeport' => "firewall#removeport", :via => :get, :as => :firewall_removeport
  post 'firewall/addservice' => "firewall#addservice", :via => :post, :as => :firewall_addservice
  post 'firewall/addport' => "firewall#addport", :via => :post, :as => :firewall_addport
  
  get 'httpd/index'
  get 'httpd/nohttpd'
  get 'httpd/install'
  
  post 'httpd/create' => "httpd#create", :via => :post, :as => :httpd_create
  post 'httpd/advance' => "httpd#advance", :via => :post, :as => :httpd_advance
  get 'httpd/delete' => "httpd#delete", :via => :get, :as => :httpd_delete
  get 'repo/index'
  get 'repo/disable' => "repo#disable", :via => :get, :as => :repo_disable
  get 'usermanagement/index'
  post 'usermanagement/create' => "usermanagement#create", :via => :post, :as => :usermanagement_create
  get 'usermanagement/destroy/:username' => "usermanagement#destroy", :via => :get, :as => :usermanagement_destory
  get 'dashboard/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/httpd_controller.rb
class HttpdController < ApplicationController
  def index
	
    x = `ls /usr/lib/systemd/system | grep httpd.service`
    if x != ""
			conffiles = `ls /etc/httpd/conf.d/nano*`
			@list = []
			split = conffiles.split(" ")
			split.each do |i|
				servername = `cat #{i} | grep -i servername | awk '{print $2}'`
				documentroot = `cat #{i} /etc/httpd/conf.d/one.conf | grep -i documentroot | awk '{print $2}'`
				portno = `cat #{i} | grep -i '^<virtualhost' | awk -F ':' '{print $2}' | sed 's/[^0-9]*//g'`
				@list << {
				:file => i,
        :servername => `cat #{i} | grep -i servername | awk '{print $2}'`,
        :documentroot => `cat #{i}  | grep -i documentroot | awk '{print $2}'`,
        :port => `cat #{i} | grep -i '^<virtualhost' | awk -F ':' '{print $2}' | sed 's/[^0-9]*//g'`
       }	
			end
			
			@json = JSON.parse(@list.to_json)
		
       render 'index'
    else
	     render 'nohttpd'
    end
  end
  
  def install 
    if `yum install httpd -y`
        render 'index'
    else
        render plain: "Error in install httpd"
    end
  
  end
	
	def create
    getservername = params[:servername]
    getdocumentroot = params[:documentroot]
		getport = params[:port]
    
		system("mkdir -p #{getdocumentroot}")
		
		zz = getservername.split('.')
		xyz = system("ls /etc/httpd/conf.d/nano#{zz[0]}")
		if xyz != "true"
			x = `echo -e "<VirtualHost *:#{getport}> \n ServerName #{getservername} \n DocumentRoot #{getdocumentroot} \n <VirtualHost>" >> /etc/httpd/conf.d/nano#{zz[0]}.conf` 
			if x
				system("systemctl restart httpd")
				system("systemctl enable httpd")
				redirect_to httpd_index_path
			else
				render plain: "Error in creating virtualhost"
			end
			
		else
			render plain: "Error server already"
		end
		
  end
	
	def advance
		requireip = params[:requireip]
    requirehost = params[:requirehost]
		if requireip == "" || requirehost == ""
		
		end
	end
	
	def delete
		xx = params[:server]
		zz = xx.split('.')
		system("rm -f /etc/httpd/conf.d/#{zz}.conf")
		system("systemctl restart httpd")
		
	end
  
end

app/helpers/httpd_helper.rb
module HttpdHelper
end

app/views/httpd/index.html.erb
<h1>Httpd Server</h1> 
<br>
<%= link_to "Add virtualhost", "#myModal", 'data-toggle' =>  "modal" %>
<br><br>
<h3>Virtual Hosts -</h3>





<table class="table table-striped" style="width:70%">
  <tr>
    
    <th>Server name</th>
    <th>Document root</th>
    <th>Port</th>
    <th>Conf file</th>
    <th colspan="2">Action</th>
  </tr>
 <% @json.each do |list| %>
  <tr>
    
    <td><%= list['servername'] %></td>
    <td><%= list['documentroot'] %></td>
    <td><%= list['port'] %></td>
    <td><%= list['file'] %></td>
    <td><%= link_to "advance", 'data-toggle' =>  "modal", "data-target" => "#advanceModal" %></td>
    <td><%= link_to "Delete", httpd_install_path(:server => list['servername']) %></td>
  </tr> 
<% end %>
</table>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add Virtual Host</h4>
      </div>
     
        <%= form_tag(httpd_create_path, method: 'POST')  do %>
        <div class="modal-body">
        <%= label_tag("ServerName:") %>
        <%= text_field_tag(:servername) %>
        <br><br>
        <%= label_tag("Document Root:") %>
        <%= text_field_tag(:documentroot) %>
        <br><br>
        <%= label_tag("Port:") %>
        <%= text_field_tag(:port) %>
        <br><br>
       
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= submit_tag("Create",:class => 'btn btn-primary') %>
      </div>
      <% end %>
    </div>
  </div>
</div>



<!-- Advance Modal -->
<div class="modal fade" id="advanceModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Advance</h4>
      </div>
     
        <%= form_tag(httpd_advance_path, method: 'POST')  do %>
        <div class="modal-body">
        <%= label_tag("Require IP:") %>
        <%= text_field_tag(:requireip) %>
        <br><br>
        <%= label_tag("Require Host:") %>
        <%= text_field_tag(:requirehost) %>
      
        <br><br>
       
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= submit_tag("Submit",:class => 'btn btn-primary') %>
      </div>
      <% end %>
    </div>
  </div>
</div>
 

app/views/httpd/nohttpd.html.erb
<h4>Http is not installed.  <%= link_to "Click here", httpd_install_path %> to install</h4>