config/routes.rb
Rails.application.routes.draw do


  get 'iscsi/index'

  get 'nfs/index'

  get 'fstab/index'
  get 'fstab/remove'
  
  get 'samba/index'
  get 'samba/install'
  get 'samba/delete'
  
  post 'samba/createshare' => "samba#createshare", :via => :post, :as => :samba_createshare

  get 'firewall/index'
  get 'firewall/removeservice', :via => :get, :as => :firewall_removeservice
  get 'firewall/removeport' => "firewall#removeport", :via => :get, :as => :firewall_removeport
  post 'firewall/addservice' => "firewall#addservice", :via => :post, :as => :firewall_addservice
  post 'firewall/addport' => "firewall#addport", :via => :post, :as => :firewall_addport
  
  get 'httpd/index'
  get 'httpd/nohttpd'
  get 'httpd/install'
  
  post 'httpd/create' => "httpd#create", :via => :post, :as => :httpd_create
  post 'httpd/advance' => "httpd#advance", :via => :post, :as => :httpd_advance
  get 'httpd/delete' => "httpd#delete", :via => :get, :as => :httpd_delete
  get 'repo/index'
  get 'repo/disable' => "repo#disable", :via => :get, :as => :repo_disable
  get 'usermanagement/index'
  post 'usermanagement/create' => "usermanagement#create", :via => :post, :as => :usermanagement_create
  get 'usermanagement/destroy/:username' => "usermanagement#destroy", :via => :get, :as => :usermanagement_destory
  get 'dashboard/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/samba_controller.rb
class SambaController < ApplicationController
  def index
     x = `ls /usr/lib/systemd/system | grep smb.service`
    if x != ""
			shares = `cat /etc/samba/smb.conf | grep '\\['`
      splits = shares.split(" ")
      
 			@list = []
			
 			splits.each do |i|

				
				@list << {
				  :sharename => i,
	 				:path => `cat /etc/samba/smb.conf | grep '\[#{i}\]' -A 6 | grep -i path | awk '{print $3}'`,
	 				:browseable => `cat /etc/samba/smb.conf | grep '\[#{i}\]' -A 6 | grep -i browseable | awk '{print $3}'`,
					:validusers => `cat /etc/samba/smb.conf | grep '\[#{i}\]' -A 6 | grep -i 'valid users' | cut -d' ' -f4-`,
					:writelist => `cat /etc/samba/smb.conf | grep '\[#{i}\]' -A 6 | grep -i 'write list' | cut -d' ' -f4-`,		
					:readlist => `cat /etc/samba/smb.conf | grep '\[#{i}\]' -A 6 | grep -i 'read list' | cut -d' ' -f4-`
       }	
			end
			
			@json = JSON.parse(@list.to_json)
		
       render 'index'
    else
	     render 'nosamba'
    end
  end

  def install
    if `yum install samba samba-client -y`
        render 'index'
    else
        render plain: "Error in install samba"
    end
  end
  
  
  def delete
  	 share = params[:share]
		puts "====+++++====="
		puts share.gsub("]", "\\]").gsub("[", "\\[")
		`sed -i '/#{share.gsub("]", "\\]").gsub("[", "\\[")}/,/^\s*$/{d}' /etc/samba/smb.conf`
# 				if x
# 				system("systemctl restart smb nmb")
# 				system("systemctl enable smb nmb")
# 				redirect_to samba_index_path
# 			else
# 				render plain: "Error in deleting samba share"
# 			end
		redirect_to samba_index_path
  end
  
	def createshare
			sharename = params[:sharename]
			path = params[:path]
			browseable = params[:browseable]
			validusers = params[:validusers]
			readlist = params[:readlist]
			writelist = params[:writelist]
			puts sharename
			puts path
			puts browseable
			puts validusers
			puts readlist
			puts writelist
			x = `echo -e "[#{sharename}] \n path = #{path} \n browseable = #{browseable} \n validusers = #{validusers} \n readlist = #{readlist} \n writelist = #{writelist}" >> /etc/samba/smb.conf`
				if x
				system("systemctl restart smb nmb")
				system("systemctl enable smb nmb")
				redirect_to samba_index_path
			else
				render plain: "Error in creating samba share"
			end
		
		
	end
  
end

app/helpers/samba_helper.rb
module SambaHelper
end

app/views/samba/index.html.erb
<h1>Samba Server</h1>
 <%= link_to "Create Share", "#myModal", 'data-toggle' =>  "modal" %>

<table class="table table-striped" style="width:70%">
  <tr>
    
    <th>Share Name</th>
    <th>Path</th>
    <th>Browseable</th>
    <th>Valid users</th>
    <th>Read list</th>
    <th>Write list</th>
    <th>Actions</th>
  </tr>
 <% @json.each do |list| %>
  <tr>
    
    <td><%= list['sharename'] %></td>
    <td><%= list['path'] %></td>
    <td><%= list['browseable'] %></td>
    <td><%= list['validusers'] %></td>
    <td><%= list['readlist'] %></td>
    <td><%= list['writelist'] %></td>
    
    
    
    <td><%= link_to "Delete", samba_delete_path(:share => list['sharename']) %></td>
  </tr> 
<% end %>
</table>

<!-- Samba Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Create Samba Share</h4>
      </div>
     
        <%= form_tag(samba_createshare_path, method: 'POST')  do %>
        <div class="modal-body">
        <%= label_tag("Share Name:") %>
        <%= text_field_tag(:sharename) %>
        <br><br>
        <%= label_tag("path:") %>
        <%= text_field_tag(:path) %>
        <br><br>  
         <%= label_tag("Browseable:") %>
        <%= radio_button_tag 'browseable', 'yes' %> YES
          
          <%= radio_button_tag 'browseable', 'no' %> NO
        <br><br>
           <%= label_tag("valid users:") %>
        <%= text_field_tag(:validusers) %>
        <br><br>
            <%= label_tag("Read list:") %>
        <%= text_field_tag(:readlist) %>
        <br><br>
            <%= label_tag("Write list:") %>
        <%= text_field_tag(:writelist) %>
        <br><br>
          
          
      
       
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= submit_tag("Add",:class => 'btn btn-primary') %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/samba/nosamba.html.erb
<h4>samba is not installed.  <%= link_to "Click here", samba_install_path %> to install</h4>