config/routes.rb
Rails.application.routes.draw do


  get 'iscsi/index'

  get 'nfs/index'

  get 'fstab/index'
  get 'fstab/remove'
  
  get 'samba/index'
  get 'samba/install'
  get 'samba/delete'
  
  post 'samba/createshare' => "samba#createshare", :via => :post, :as => :samba_createshare

  get 'firewall/index'
  get 'firewall/removeservice', :via => :get, :as => :firewall_removeservice
  get 'firewall/removeport' => "firewall#removeport", :via => :get, :as => :firewall_removeport
  post 'firewall/addservice' => "firewall#addservice", :via => :post, :as => :firewall_addservice
  post 'firewall/addport' => "firewall#addport", :via => :post, :as => :firewall_addport
  
  get 'httpd/index'
  get 'httpd/nohttpd'
  get 'httpd/install'
  
  post 'httpd/create' => "httpd#create", :via => :post, :as => :httpd_create
  post 'httpd/advance' => "httpd#advance", :via => :post, :as => :httpd_advance
  get 'httpd/delete' => "httpd#delete", :via => :get, :as => :httpd_delete
  get 'repo/index'
  get 'repo/disable' => "repo#disable", :via => :get, :as => :repo_disable
  get 'usermanagement/index'
  post 'usermanagement/create' => "usermanagement#create", :via => :post, :as => :usermanagement_create
  get 'usermanagement/destroy/:username' => "usermanagement#destroy", :via => :get, :as => :usermanagement_destory
  get 'dashboard/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/firewall_controller.rb
class FirewallController < ApplicationController
  def index
    x = `firewall-cmd --list-all | grep services`
    @test = x.split(" ")
    @test.delete_at(0)
    
    x2 = `firewall-cmd --list-all | grep -m 1 'ports'`
    @ports = x2.split(" ")
    @ports.delete_at(0)
  end
  
  def addservice
    service = params[:service]
    system("firewall-cmd --permanent --add-service=#{service}")
    system("firewall-cmd --reload")
    redirect_to firewall_index_path
  end
  
  def addport
    port = params[:fport]
    system("firewall-cmd --permanent --add-port=#{port}/tcp")
    system("firewall-cmd --reload")
    redirect_to firewall_index_path
  end
  
  def removeservice
    service = params[:service]
    
    system("firewall-cmd --permanent --remove-service=#{service}")
    system("firewall-cmd --reload")
    redirect_to firewall_index_path
  end
  
  def removeport
    port = params[:fport]
    
    system("firewall-cmd --permanent --remove-port=#{port}")
    system("firewall-cmd --reload")
    redirect_to firewall_index_path
  end
end

app/helpers/firewall_helper.rb
module FirewallHelper
end

app/views/firewall/index.html.erb
<h1>Firewall</h1>



<div class="row">
<div class="col-lg-5">
<h4>Services</h4>
 
  <%= link_to "Add Service", "#myModal", 'data-toggle' =>  "modal" %>
  <br><br>
<table class="table table-striped" style="width:50%">
  <tr>
    <th>Services</th>
    <th>Action</th>
  </tr>
  <% @test.each do |service| %>
  <tr>
    <td><%= service %></td>   
    <td><%= link_to "Remove", firewall_removeservice_path(:service => service) %></td>    
  </tr> 
   <% end %>
</table>
</div>
<div class="col-lg-5">
 
  <h4>Port</h4>
 
  <%= link_to "Add port", "#myportModal", 'data-toggle' =>  "modal" %>
  <br><br>
  
<table class="table table-striped" style="width:50%">
  <tr>
    <th>Ports</th>
    <th>Action</th>
  </tr>
  <% @ports.each do |port| %>
  <tr>
    <td><%= port %></td>   
    <td><%= link_to "Remove", firewall_removeport_path(:fport => port) %></td>    
  </tr> 
   <% end %>
</table>
  
</div>

</div>


<!-- Service Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add service in firewall</h4>
      </div>
     
        <%= form_tag(firewall_addservice_path, method: 'POST')  do %>
        <div class="modal-body">
        <%= label_tag("Service name:") %>
        <%= text_field_tag(:service) %>
        <br><br>
      
       
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= submit_tag("Add",:class => 'btn btn-primary') %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<!-- port Modal -->
<div class="modal fade" id="myportModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add port in firewall</h4>
      </div>
     
        <%= form_tag(firewall_addport_path, method: 'POST')  do %>
        <div class="modal-body">
        <%= label_tag("Port no.:") %>
        <%= number_field_tag 'fport', nil, min:1 %>
        <br><br>
      
       
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= submit_tag("Add",:class => 'btn btn-primary') %>
      </div>
      <% end %>
    </div>
  </div>
</div>