config/routes.rb
Rails.application.routes.draw do


  get 'iscsi/index'

  get 'nfs/index'

  get 'fstab/index'
  get 'fstab/remove'
  
  get 'samba/index'
  get 'samba/install'
  get 'samba/delete'
  
  post 'samba/createshare' => "samba#createshare", :via => :post, :as => :samba_createshare

  get 'firewall/index'
  get 'firewall/removeservice', :via => :get, :as => :firewall_removeservice
  get 'firewall/removeport' => "firewall#removeport", :via => :get, :as => :firewall_removeport
  post 'firewall/addservice' => "firewall#addservice", :via => :post, :as => :firewall_addservice
  post 'firewall/addport' => "firewall#addport", :via => :post, :as => :firewall_addport
  
  get 'httpd/index'
  get 'httpd/nohttpd'
  get 'httpd/install'
  
  post 'httpd/create' => "httpd#create", :via => :post, :as => :httpd_create
  post 'httpd/advance' => "httpd#advance", :via => :post, :as => :httpd_advance
  get 'httpd/delete' => "httpd#delete", :via => :get, :as => :httpd_delete
  get 'repo/index'
  get 'repo/disable' => "repo#disable", :via => :get, :as => :repo_disable
  get 'usermanagement/index'
  post 'usermanagement/create' => "usermanagement#create", :via => :post, :as => :usermanagement_create
  get 'usermanagement/destroy/:username' => "usermanagement#destroy", :via => :get, :as => :usermanagement_destory
  get 'dashboard/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nano Satellite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>

  <body>
    
    <nav class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="" href="#"></a>
      <%= link_to "Nano Satellite", dashboard_index_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administrative<span class="caret"></span></a>
          <ul class="dropdown-menu">
            
            <li><%= link_to "User / Group Management", usermanagement_index_path %></li>
<!--             <li><a href="#">User / Group Management</a></li> -->
            <li><a href="#">File Permissions</a></li>
             <li><%= link_to "Repos", repo_index_path %></li>
            
            <li role="separator" class="divider"></li>
            <li><%= link_to "Firewall", firewall_index_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Mount points", fstab_index_path %></li>
          </ul>
        </li>
        
       
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Advance<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Httpd", httpd_index_path %></li>
            <li><%= link_to "Samba Server", samba_index_path %></li>
            <li><%= link_to "NFS Server", nfs_index_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Iscsi", iscsi_index_path %></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Logout</a></li>
       
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">
    
    <%= yield %>
     
      </div>    
 
  </body>
</html>